# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.book import Book  # noqa: F401,E501
from swagger_server import util


class BookListResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, success: bool=None, data: List[Book]=None, message: str=None):  # noqa: E501
        """BookListResponse - a model defined in Swagger

        :param success: The success of this BookListResponse.  # noqa: E501
        :type success: bool
        :param data: The data of this BookListResponse.  # noqa: E501
        :type data: List[Book]
        :param message: The message of this BookListResponse.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'success': bool,
            'data': List[Book],
            'message': str
        }

        self.attribute_map = {
            'success': 'success',
            'data': 'data',
            'message': 'message'
        }
        self._success = success
        self._data = data
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'BookListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookListResponse of this BookListResponse.  # noqa: E501
        :rtype: BookListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this BookListResponse.


        :return: The success of this BookListResponse.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this BookListResponse.


        :param success: The success of this BookListResponse.
        :type success: bool
        """

        self._success = success

    @property
    def data(self) -> List[Book]:
        """Gets the data of this BookListResponse.


        :return: The data of this BookListResponse.
        :rtype: List[Book]
        """
        return self._data

    @data.setter
    def data(self, data: List[Book]):
        """Sets the data of this BookListResponse.


        :param data: The data of this BookListResponse.
        :type data: List[Book]
        """

        self._data = data

    @property
    def message(self) -> str:
        """Gets the message of this BookListResponse.


        :return: The message of this BookListResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this BookListResponse.


        :param message: The message of this BookListResponse.
        :type message: str
        """

        self._message = message
