# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CreateBookRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, author: str=None, genre: str=None, published_year: int=None, price: float=None, is_available: bool=None):  # noqa: E501
        """CreateBookRequest - a model defined in Swagger

        :param title: The title of this CreateBookRequest.  # noqa: E501
        :type title: str
        :param author: The author of this CreateBookRequest.  # noqa: E501
        :type author: str
        :param genre: The genre of this CreateBookRequest.  # noqa: E501
        :type genre: str
        :param published_year: The published_year of this CreateBookRequest.  # noqa: E501
        :type published_year: int
        :param price: The price of this CreateBookRequest.  # noqa: E501
        :type price: float
        :param is_available: The is_available of this CreateBookRequest.  # noqa: E501
        :type is_available: bool
        """
        self.swagger_types = {
            'title': str,
            'author': str,
            'genre': str,
            'published_year': int,
            'price': float,
            'is_available': bool
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author',
            'genre': 'genre',
            'published_year': 'published_year',
            'price': 'price',
            'is_available': 'is_available'
        }
        self._title = title
        self._author = author
        self._genre = genre
        self._published_year = published_year
        self._price = price
        self._is_available = is_available

    @classmethod
    def from_dict(cls, dikt) -> 'CreateBookRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateBookRequest of this CreateBookRequest.  # noqa: E501
        :rtype: CreateBookRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this CreateBookRequest.


        :return: The title of this CreateBookRequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this CreateBookRequest.


        :param title: The title of this CreateBookRequest.
        :type title: str
        """

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this CreateBookRequest.


        :return: The author of this CreateBookRequest.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this CreateBookRequest.


        :param author: The author of this CreateBookRequest.
        :type author: str
        """

        self._author = author

    @property
    def genre(self) -> str:
        """Gets the genre of this CreateBookRequest.


        :return: The genre of this CreateBookRequest.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this CreateBookRequest.


        :param genre: The genre of this CreateBookRequest.
        :type genre: str
        """

        self._genre = genre

    @property
    def published_year(self) -> int:
        """Gets the published_year of this CreateBookRequest.


        :return: The published_year of this CreateBookRequest.
        :rtype: int
        """
        return self._published_year

    @published_year.setter
    def published_year(self, published_year: int):
        """Sets the published_year of this CreateBookRequest.


        :param published_year: The published_year of this CreateBookRequest.
        :type published_year: int
        """

        self._published_year = published_year

    @property
    def price(self) -> float:
        """Gets the price of this CreateBookRequest.


        :return: The price of this CreateBookRequest.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this CreateBookRequest.


        :param price: The price of this CreateBookRequest.
        :type price: float
        """

        self._price = price

    @property
    def is_available(self) -> bool:
        """Gets the is_available of this CreateBookRequest.


        :return: The is_available of this CreateBookRequest.
        :rtype: bool
        """
        return self._is_available

    @is_available.setter
    def is_available(self, is_available: bool):
        """Sets the is_available of this CreateBookRequest.


        :param is_available: The is_available of this CreateBookRequest.
        :type is_available: bool
        """

        self._is_available = is_available
