openapi: 3.0.0
info:
  title: Book API
  version: 1.0.0
servers:
  - url: http://localhost:5000
  - url: http://2526-ii-int-3505-1-gpf3-2g8bjq0ny-dinhhoccodes-projects.vercel.app
paths:
  /api/v1/books:
    get:
      summary: Lấy danh sách sách
      responses:
        "200":
          description: Lấy danh sách sách thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookListResponse" 
      
    post:
      summary: Tạo sách mới
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBookRequest"
      responses:
        "201":
          description: Tạo sách thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookResponse"

  /api/v1/books/search:
    get: 
      summary: Tìm kiếm sách
      parameters:
        - name: title
          in: query
          required: false
          description: Tìm kiếm theo tiêu đề sách
          schema:
            type: string
      responses:
        "200":
          description: Tìm kiếm sách thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookListResponse"

  /api/v1/books/{book_id}:
    get: 
      summary: Lấy thông tin sách theo id
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Lấy thông tin sách thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookResponse"
        "404":
          description: không tìm thấy sách

    put: 
      summary: Cập nhật thông tin sách
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBookRequest"
      responses:
        "200":
          description: Cập nhật thông tin sách thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookResponse"
        "404":
          description: không tìm thấy sách
    patch:
      summary: Cập nhật một phần sách
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookResponse"
        "404":
          description: Không tìm thấy sách
    delete: 
      summary: Xóa sách
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Xóa sách thành công
components:
  schemas:

    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
        genre:
          type: string
        published_year:
          type: integer
        price:
          type: number
          format: float
        is_available:
          type: boolean

    CreateBookRequest:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        genre:
          type: string
        published_year:
          type: integer
        price:
          type: number
        is_available:
          type: boolean

    BookResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: "#/components/schemas/Book"
        message:
          type: string

    BookListResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            $ref: "#/components/schemas/Book"
        message:
          type: string