openapi: 3.0.0
info:
  title: Library API
  version: 1.0.0
servers:
  - url: https://2526-ii-int-3505-1-4967-git-main-dinhhoccodes-projects.vercel.app

paths:
  /books:
    get:
      summary: Get all books
      responses:
        "200":
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

    post:
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookRequest'
      responses:
        "201":
          description: Book created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

        "400":
          description: Missing required fields

  /books/{id}:
    get:
      summary: Get book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Book detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

        "404":
          description: Book not found

    put:
      summary: Update book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookRequest'
      responses:
        "200":
          description: Updated book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

        "400":
          description: Missing required fields

        "404":
          description: Book not found

    delete:
      summary: Delete book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Deleted successfully

        "404":
          description: Book not found

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string

    CreateBookRequest:
      type: object
      required:
        - title
        - author
      properties:
        title:
          type: string
        author:
          type: string