openapi: 3.0.0
info:
  title: Library API
  version: v1
servers:
- url: https://2526-ii-int-3505-1-4967.vercel.app/
paths:
  /books:
    get:
      description: Get all books
      operationId: g_et_books
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Book"
                type: array
          description: ""
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      description: Create a new book
      operationId: p_ost_books
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBookRequest"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
          description: ""
        "400":
          description: Missing required fields
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /books/{id}:
    delete:
      description: Delete book
      operationId: d_elete_books_id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "204":
          description: Deleted successfully
        "404":
          description: Book not found
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      description: Get book by ID
      operationId: g_et_books_id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
          description: ""
        "404":
          description: Book not found
      x-openapi-router-controller: openapi_server.controllers.default_controller
    put:
      description: Update book
      operationId: p_ut_books_id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBookRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
          description: ""
        "400":
          description: Missing required fields
        "404":
          description: Book not found
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  callbacks: {}
  examples: {}
  headers: {}
  links: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas:
    Book:
      example:
        author: author
        id: 0
        title: title
      properties:
        id:
          title: id
          type: integer
        title:
          title: title
          type: string
        author:
          title: author
          type: string
      required:
      - author
      - id
      - title
      title: Book
      type: object
    CreateBookRequest:
      example:
        author: author
        title: title
      properties:
        title:
          title: title
          type: string
        author:
          title: author
          type: string
      required:
      - author
      - title
      title: CreateBookRequest
      type: object
  securitySchemes: {}
