from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from OpenAPISpec.models.base_model import Model
from OpenAPISpec.models.book import Book
from OpenAPISpec import util

from OpenAPISpec.models.book import Book  # noqa: E501

class BookResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, data=None, message=None):  # noqa: E501
        """BookResponse - a model defined in OpenAPI

        :param success: The success of this BookResponse.  # noqa: E501
        :type success: bool
        :param data: The data of this BookResponse.  # noqa: E501
        :type data: Book
        :param message: The message of this BookResponse.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'success': bool,
            'data': Book,
            'message': str
        }

        self.attribute_map = {
            'success': 'success',
            'data': 'data',
            'message': 'message'
        }

        self._success = success
        self._data = data
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'BookResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookResponse of this BookResponse.  # noqa: E501
        :rtype: BookResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this BookResponse.


        :return: The success of this BookResponse.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this BookResponse.


        :param success: The success of this BookResponse.
        :type success: bool
        """

        self._success = success

    @property
    def data(self) -> Book:
        """Gets the data of this BookResponse.


        :return: The data of this BookResponse.
        :rtype: Book
        """
        return self._data

    @data.setter
    def data(self, data: Book):
        """Sets the data of this BookResponse.


        :param data: The data of this BookResponse.
        :type data: Book
        """

        self._data = data

    @property
    def message(self) -> str:
        """Gets the message of this BookResponse.


        :return: The message of this BookResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this BookResponse.


        :param message: The message of this BookResponse.
        :type message: str
        """

        self._message = message
