from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from OpenAPISpec.models.base_model import Model
from OpenAPISpec import util


class Book(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, title=None, author=None, genre=None, published_year=None, price=None, is_available=None):  # noqa: E501
        """Book - a model defined in OpenAPI

        :param id: The id of this Book.  # noqa: E501
        :type id: int
        :param title: The title of this Book.  # noqa: E501
        :type title: str
        :param author: The author of this Book.  # noqa: E501
        :type author: str
        :param genre: The genre of this Book.  # noqa: E501
        :type genre: str
        :param published_year: The published_year of this Book.  # noqa: E501
        :type published_year: int
        :param price: The price of this Book.  # noqa: E501
        :type price: float
        :param is_available: The is_available of this Book.  # noqa: E501
        :type is_available: bool
        """
        self.openapi_types = {
            'id': int,
            'title': str,
            'author': str,
            'genre': str,
            'published_year': int,
            'price': float,
            'is_available': bool
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'author': 'author',
            'genre': 'genre',
            'published_year': 'published_year',
            'price': 'price',
            'is_available': 'is_available'
        }

        self._id = id
        self._title = title
        self._author = author
        self._genre = genre
        self._published_year = published_year
        self._price = price
        self._is_available = is_available

    @classmethod
    def from_dict(cls, dikt) -> 'Book':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Book of this Book.  # noqa: E501
        :rtype: Book
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Book.


        :return: The id of this Book.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Book.


        :param id: The id of this Book.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Book.


        :return: The title of this Book.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Book.


        :param title: The title of this Book.
        :type title: str
        """

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this Book.


        :return: The author of this Book.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this Book.


        :param author: The author of this Book.
        :type author: str
        """

        self._author = author

    @property
    def genre(self) -> str:
        """Gets the genre of this Book.


        :return: The genre of this Book.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this Book.


        :param genre: The genre of this Book.
        :type genre: str
        """

        self._genre = genre

    @property
    def published_year(self) -> int:
        """Gets the published_year of this Book.


        :return: The published_year of this Book.
        :rtype: int
        """
        return self._published_year

    @published_year.setter
    def published_year(self, published_year: int):
        """Sets the published_year of this Book.


        :param published_year: The published_year of this Book.
        :type published_year: int
        """

        self._published_year = published_year

    @property
    def price(self) -> float:
        """Gets the price of this Book.


        :return: The price of this Book.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Book.


        :param price: The price of this Book.
        :type price: float
        """

        self._price = price

    @property
    def is_available(self) -> bool:
        """Gets the is_available of this Book.


        :return: The is_available of this Book.
        :rtype: bool
        """
        return self._is_available

    @is_available.setter
    def is_available(self, is_available: bool):
        """Sets the is_available of this Book.


        :param is_available: The is_available of this Book.
        :type is_available: bool
        """

        self._is_available = is_available
