openapi: 3.0.0
info:
  title: Library API
  version: 1.0.0
  description: API quản lý sách đơn giản sử dụng Flask.
tags: []
paths:
  /books:
    get:
      operationId: Books_getBooks
      summary: Lấy danh sách toàn bộ sách
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      operationId: Books_createBook
      summary: Thêm sách mới
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            text/plain:
              schema:
                type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBook'
  /books/{id}:
    get:
      operationId: Books_getBook
      summary: Lấy thông tin một cuốn sách
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: The server cannot find the requested resource.
          content:
            text/plain:
              schema:
                type: string
    put:
      operationId: Books_updateBook
      summary: Cập nhật thông tin sách
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: The server cannot find the requested resource.
          content:
            text/plain:
              schema:
                type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBook'
    delete:
      operationId: Books_deleteBook
      summary: Xóa sách
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '404':
          description: The server cannot find the requested resource.
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Book:
      type: object
      required:
        - id
        - title
        - author
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
        author:
          type: string
    NewBook:
      type: object
      required:
        - title
        - author
      properties:
        title:
          type: string
        author:
          type: string
servers:
  - url: https://2526-ii-int-3505-1-4967.vercel.app/
    variables: {}
